# A workflow to keep Huggingface Alive

name: Huggingface Keep-Alive

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # Specify environment
    environment: HugginFace-free
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Huggingface Keep-Alive Ping
        run: |
         echo "讀取 Job env: $HF_SPACE_URL"
         curl "${{ vars.HF_SPACE_URL }}"

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
      - name: Notify n8n Webhook
        # 關鍵：確保前面步驟失敗時，此步驟仍會執行
        if: always() 
        run: |
          curl -X POST https://robert-ck-n8n-free.hf.space/webhook-test/a4b83bbe-4624-43a7-8f93-3e792d939b26 \
          -H 'Content-Type: application/json' \
          -d '{
            "event": "${{ github.event_name }}",
            "repository": "${{ github.repository }}",
            "workflow": "${{ github.workflow }}",
            "run_id": "${{ github.run_id }}",
            "status": "${{ job.status }}",
            "actor": "${{ github.actor }}",
            "run_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
